# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(help_text='Identificador único (ex: vitrine, deposito)', unique=True, verbose_name='Ref')),
                ('name', models.CharField(help_text='Nome legível da posição', max_length=100, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('physical', 'Físico'), ('process', 'Produção'), ('virtual', 'Virtual')], default='physical', max_length=20, verbose_name='Tipo')),
                ('is_saleable', models.BooleanField(default=False, help_text='Se True, estoque aqui pode ser vendido diretamente.', verbose_name='Permite venda')),
                ('is_default', models.BooleanField(default=False, help_text='Se True, esta é a posição padrão para novos Quants.', verbose_name='Posição padrão')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados da posição. Ex: {"temperature": "ambiente", "capacity": 500}', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Identificador único do lote (ex: CRO-20260319-M).', max_length=50, unique=True, verbose_name='Referência do Lote')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Data de Produção')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Último dia em que o lote pode ser vendido/utilizado', null=True, verbose_name='Data de Validade')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['expiry_date', 'production_date'],
                'indexes': [models.Index(fields=['sku'], name='stockman_ba_sku_idx'), models.Index(fields=['expiry_date'], name='stockman_ba_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('target_date', models.DateField(blank=True, db_index=True, help_text='Vazio = estoque físico. Data = produção planejada.', null=True, verbose_name='Data Alvo')),
                ('batch', models.CharField(blank=True, default='', help_text='Referência do lote (Batch.ref). Vazio = sem lote.', max_length=50, verbose_name='Lote')),
                ('_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Quantidade')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do quant. Ex: {"batch": "2024-01", "supplier": "Moinho SP"}', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quants', to='stockman.position', verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=3, help_text='Positivo = entrada, Negativo = saída', max_digits=12, verbose_name='Variação')),
                ('reason', models.CharField(help_text='Obrigatório. Ex: "Produção manhã", "Venda #123"', max_length=255, verbose_name='Motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do movimento. Ex: {"reason_detail": "Ajuste de inventário"}', verbose_name='Metadados')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('quant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='stockman.quant', verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('target_date', models.DateField(db_index=True, verbose_name='Data Desejada')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('fulfilled', 'Concluído'), ('released', 'Liberado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Se não concluído até esta data, será liberado automaticamente', null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Data de fulfillment ou release', null=True, verbose_name='Resolvido em')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('quant', models.ForeignKey(blank=True, help_text='Vazio = demanda (cliente quer, mas não há estoque)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='stockman.quant', verbose_name='Estoque Vinculado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('min_quantity', models.DecimalField(decimal_places=3, help_text='Alerta dispara quando disponível < este valor', max_digits=12, verbose_name='Quantidade Mínima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Último disparo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('position', models.ForeignKey(blank=True, help_text='Vazio = soma de todas as posições', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stockman.position', verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
            },
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['sku'], name='stockman_qu_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['target_date'], name='stockman_qu_target_idx'),
        ),
        migrations.AddIndex(
            model_name='quant',
            index=models.Index(fields=['position', 'target_date'], name='stockman_qu_pos_tgt_idx'),
        ),
        migrations.AddConstraint(
            model_name='quant',
            constraint=models.UniqueConstraint(fields=('sku', 'position', 'target_date', 'batch'), name='unique_quant_coordinate'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['quant', 'timestamp'], name='stockman_mo_quant_i_cef5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['timestamp'], name='stockman_mo_timesta_79df8d_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['status', 'expires_at'], name='stockman_ho_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['sku', 'target_date'], name='stockman_ho_sku_tgt_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['status', 'quant'], name='stockman_ho_status_qnt_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['sku'], name='stockman_sa_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['is_active'], name='stockman_sa_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(fields=('sku', 'position'), name='unique_stock_alert_per_sku_position'),
        ),
    ]
